server:
  port: '8080'
spring:
  profiles:
    active: dev
---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: user_1
    url: jdbc:mariadb://localhost:3306/dcbapp
    password: test123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "beans,env"
---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: user_1
    url: jdbc:mariadb://localhost:3306/dcbapp_prod
    password: test123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

---

spring:
  config:
    activate:
      on-profile: qa
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: user_1
    url: jdbc:mariadb://localhost:3306/dcbapp_qa
    password: test123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

